export const API_BASE_URL = 'http://localhost:8080/api';

export const USER_TYPES = {
  IMPORTATEUR: 'IMPORTATEUR',
  AGENT: 'AGENT',
  SUPERVISEUR: 'SUPERVISEUR' // Ajout explicite du superviseur
};

export const STATUS_DEMANDE = {
  DEPOSE: 'DEPOSE',
  EN_COURS_DE_TRAITEMENT: 'EN_COURS_DE_TRAITEMENT',
  CLOTURE: 'CLOTURE'
};

export const CATEGORIES_MARCHANDISE = [
  'PRODUITS_INDUSTRIELS_ET_TECHNIQUES',
  'VEHICULES_ET_PIECES_DETACHEES',
  'EQUIPEMENTS_ECLAIRAGE',
  'JOUETS_ET_ARTICLES_ENFANTS',
  'MATERIEL_ELECTRIQUE_ET_CABLAGE',
  'MEUBLES_ET_ARTICLES_BOIS',
  'PRODUITS_AGROALIMENTAIRES',
  'PRODUITS_PHARMACEUTIQUES_ET_COSMETIQUES',
  'TEXTILE_ET_HABILLEMENT',
  'EQUIPEMENTS_INFORMATIQUES_ET_TELECOMMUNICATION',
  'PRODUITS_CHIMIQUES',
  'EMBALLAGES_ET_PRODUITS_PLASTIQUE',
  'PRODUITS_PETROLIERS_ET_LUBRIFIANTS',
  'PRODUITS_CULTURELS_ET_EDUCATIFS',
  'PRODUITS_AGRICOLES_ANIMAUX_VIVANTS'
];

export const UNITES_QUANTITE = [
  'PIECE', 'KG', 'TONNE', 'LITRE', 'M2', 'M3', 'CARTON', 'PALETTE'
];

export const AVIS_MARCHANDISE = {
  CONFORME: 'CONFORME',
  NON_CONFORME: 'NON_CONFORME',
  CONFORME_AVEC_RESERVE: 'CONFORME_AVEC_RESERVE'
};